// <auto-generated />
using FirstProject.ArticleAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstProject.ArticleAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FirstProject.ArticleAPI.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Data")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            AuthorId = 1,
                            CategoryId = 3,
                            Content = "Если зайти сейчас в салон связи и начать выбирать себе кнопочник, то можно обнаружить огромное количество самых разных девайсов на любой карман: и телефоны за 500 рублей, и телефоны от HMD Global под брендом Nokia, и современные 4G кнопочные смартфоны. Но на вторичном рынке продолжают пользоваться спросом и Б/У флагманы прошлых лет. Так кто же лучше - современный телефон за 1.000 рублей, или 17 летний флагман? Это вы и узнаете в сегодняшней статье!",
                            Data = 12542125234L,
                            ImageUrl = "https://habrastorage.org/getpro/habr/upload_files/c8e/210/43c/c8e21043cac1f0bd8966cf8d793452ba.webp",
                            Title = "Кнопочник новодел vs старый флагман. Смотрим на Nokia N72 и выясняем кто лучше"
                        },
                        new
                        {
                            ArticleId = 2,
                            AuthorId = 3,
                            CategoryId = 3,
                            Content = "Постановка задачи\r\n\r\nКак известно, бот это программа на компьютере, которая взаимодействует с https://api.telegram.org и притворяется человеком. Разумеется, у неё есть данные в своей собственной базе данных или типа того. Если этот компьютер внезапно исчезнет, то хотелось бы, чтобы верные друзья в другом месте и с другим компьютером «засунули флешку» и запустили этого же бота из другого места. И, разумеется, для этого нужно передать актуальные данные из старого места в новое. Разумеется, для этого существуют какие-нибудь проверенные временем дорогостоящие решения, но это всё можно организовать прямо через Телеграм. И не спрашивайте, зачем это нужно лично вам.",
                            Data = 125421255000L,
                            ImageUrl = "",
                            Title = "Как хранить данные бота прямо в Телеграме"
                        },
                        new
                        {
                            ArticleId = 3,
                            AuthorId = 31,
                            CategoryId = 3,
                            Content = "Доброго времени суток, Хабр!\r\n\r\nВ своей работе IT-специалист иногда сталкивается с задачами, которые входят только в общий кругозор на уровне \"читал, осознал\", требующими срочного решения.\r\n\r\nНедавно, после установки драйверов видеокарты NVIDIA для XFCE4 на Proxmox 7.xx перестал пинговаться гипервизор с роутера и компов сети. После его перезагрузки я увидел черный экран и надписью \"grub disk native sectors not found\".\r\n\r\nЗагрузившись с LiveUSB Ubuntu я прочитал разделы диска, убедился, что данные целы, проблема в загрузчике. Стало ясно, что проблема с разделом Grub BIOS, так как разделы диска EFI и рабочий монтировались корректно.\r\n\r\nНадо сказать, что я устанавливал Proxmox 7.xx со стандартными настройками разбиения диска, то есть три раздела GPT-диска /dev/nvme0n1: /dev/nvme0n1p1 - GrubBIOS; /dev/nvme0n1p2 - EFI диск; /dev/nvme0n1p3 - LVM раздел, в котором Proxmox по-умолчанию задает два LVM диска /dev/pve/root и /dev/pve/swap\r\n\r\nУбедившись, что данные корректны, диски fsck - тест проходят приступил к восстановлению. Я вставил поисковик текст ошибки и открыл статью-инструкцию на сайте Proxmox.\r\n\r\nСмысл ясен: грузим Linux-ОС с поддержкой LVM, активируем диск LVM с загрузчиком гипервизора, монтируем в папку, заходим chroot и восстанавливаем загрузчик (ничего сложного). Ниже листинг до проблемы, которая возникла у меня:",
                            Data = 125421255050L,
                            ImageUrl = "https://habrastorage.org/getpro/habr/upload_files/7c0/ce4/f23/7c0ce4f23dff56cc4ab71861d72fed8c.jpg",
                            Title = "Заметка о восстановлении Grub UEFI для Proxmox 7.xx (Debian 11)"
                        },
                        new
                        {
                            ArticleId = 4,
                            AuthorId = 41,
                            CategoryId = 3,
                            Content = "Приведу для начала несколько фактов, которые когда-то поспособствовали расширению лично моих горизонтов.\r\n\r\nОдна московская знакомая росла в Нью-Йорке в 70-х годах: отец работал советским специалистом в ООН. Смотрят как-то юмористическую передачу на американском TV: она, подросток, ухохатывается — отец ничего не понимает, хотя прошёл какие-то немыслимые тесты и языком владел отлично.\r\n\r\nС тех пор её работа так или иначе связана с английским. В бюро переводов, где мы познакомились, она была редактором — вычитывала уже сделанные переводы на предмет ошибок. Я знал, что она, помимо прочего, читает английскую классику в оригинале и был уверен, что разговаривает не хуже, чем по-русски. А потом случайно услышал, как она полчаса разговаривала с англичанином. Я был в шоке: у неё оказалась до чрезвычайности бедная неразнообразная речь. Почти никаких устойчивых фраз или идиом — она просто передавала мысль так, чтобы её поняли (в статье «О развитии навыка говорения» я это называю первым уровнем развития речи).",
                            Data = 125421255055L,
                            ImageUrl = "https://habrastorage.org/getpro/habr/upload_files/ad5/bb5/c45/ad5bb5c452f6130045241fd266ddb890.jpg",
                            Title = "Мифы об изучении иностранных языкове"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
